"""added_userspostsprofilesgithub_accounts

Revision ID: 075e4759c4a3
Revises: 
Create Date: 2025-11-27 21:24:48.335119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect
import geoalchemy2  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = '075e4759c4a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False, comment='Unique Clerk user identifier'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="User's full name"),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the user account is active'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='Timestamp of last successful login'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('mobile_number', sa.String(length=255), nullable=True, comment="User's mobile number"),
    sa.Column('image_url', sa.String(length=512), nullable=True, comment="User's image URL"),
    sa.PrimaryKeyConstraint('clerk_user_id', name=op.f('pk_users')),
    comment='System users with Clerk authentication integration'
    )
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('github_accounts',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for GitHub account'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='Foreign key to users table'),
    sa.Column('github_user_id', sa.BigInteger(), nullable=False, comment='Unique GitHub user identifier'),
    sa.Column('username', sa.Text(), nullable=True, comment='GitHub username'),
    sa.Column('access_token', sa.Text(), nullable=True, comment='Encrypted GitHub OAuth access token'),
    sa.Column('token_scope', sa.Text(), nullable=True, comment='OAuth token scope/permissions'),
    sa.Column('follower_count', sa.Integer(), nullable=True, comment='Number of GitHub followers'),
    sa.Column('following_count', sa.Integer(), nullable=True, comment='Number of GitHub users being followed'),
    sa.Column('public_repos', sa.Integer(), nullable=True, comment='Number of public repositories'),
    sa.Column('last_synced', sa.DateTime(), nullable=False, comment='Timestamp of last sync with GitHub API'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the GitHub account was linked'),
    sa.ForeignKeyConstraint(['user_id'], ['users.clerk_user_id'], name=op.f('github_accounts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_accounts')),
    comment='GitHub account integration for users'
    )
    op.create_index('idx_github_account_github_user_id', 'github_accounts', ['github_user_id'], unique=False)
    op.create_index('idx_github_account_user_id', 'github_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_github_accounts_github_user_id'), 'github_accounts', ['github_user_id'], unique=True)
    op.create_index(op.f('ix_github_accounts_id'), 'github_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_github_accounts_user_id'), 'github_accounts', ['user_id'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for post'),
    sa.Column('author_id', sa.String(length=255), nullable=False, comment='Foreign key to users table (post author)'),
    sa.Column('post_type', sa.String(length=30), nullable=False, comment="Post type: 'general' or 'request'"),
    sa.Column('content', sa.Text(), nullable=True, comment='Post content/text'),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Post attachments (JSON structure)'),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Post requirements (JSON structure, typically for request posts)'),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), nullable=True, comment='Array of skills related to the post'),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True, comment='Array of tags for post categorization'),
    sa.Column('github_repo_fullname', sa.Text(), nullable=True, comment="Full name of associated GitHub repository (e.g., 'vercel/next.js')"),
    sa.Column('github_repo_url', sa.Text(), nullable=True, comment='URL to the GitHub repository'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the post was created'),
    sa.Column('location_geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Geographic point (latitude, longitude) using WGS84 (SRID 4326)'),
    sa.CheckConstraint("post_type IN ('general', 'request')", name=op.f('ck_posts_ck_post_type')),
    sa.ForeignKeyConstraint(['author_id'], ['users.clerk_user_id'], name=op.f('posts_author_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts')),
    comment='User posts including general posts and request posts'
    )
    op.create_index('idx_post_author_id', 'posts', ['author_id'], unique=False)
    op.create_index('idx_post_created_at', 'posts', ['created_at'], unique=False)
    op.create_index('idx_post_type', 'posts', ['post_type'], unique=False)
    
    # Check if idx_posts_location_geog index exists before creating it
    # This handles the case where the index was created manually or in a previous failed migration
    try:
        bind = op.get_bind()
        inspector = inspect(bind)
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('posts')]
        if 'idx_posts_location_geog' not in existing_indexes:
            op.create_index('idx_posts_location_geog', 'posts', ['location_geog'], unique=False, postgresql_using='gist')
    except Exception:
        # If check fails, try to create the index anyway (will fail gracefully if it exists)
        try:
            op.create_index('idx_posts_location_geog', 'posts', ['location_geog'], unique=False, postgresql_using='gist')
        except Exception:
            pass  # Index already exists, which is fine
    
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for profile'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='Foreign key to users table'),
    sa.Column('headline', sa.Text(), nullable=True, comment='Professional headline or title'),
    sa.Column('bio', sa.Text(), nullable=True, comment="User's biography or description"),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), nullable=True, comment='Canonical list of skills'),
    sa.Column('timezone', sa.String(length=255), nullable=True, comment="User's timezone"),
    sa.Column('location_geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Geographic point (latitude, longitude) using WGS84 (SRID 4326)'),
    sa.Column('location', sa.String(length=255), nullable=True, comment="User's location/city"),
    sa.Column('state', sa.String(length=255), nullable=True, comment="User's state/province"),
    sa.Column('country', sa.String(length=255), nullable=True, comment="User's country"),
    sa.Column('pin', sa.String(length=50), nullable=True, comment='Postal/ZIP code'),
    sa.Column('district', sa.String(length=255), nullable=True, comment="User's district/region"),
    sa.Column('github_connected', sa.Boolean(), nullable=False, comment='Whether GitHub account is connected'),
    sa.Column('github_username', sa.Text(), nullable=True, comment='GitHub username if connected'),
    sa.Column('github_user_id', sa.BigInteger(), nullable=True, comment='GitHub user ID if connected'),
    sa.Column('github_last_synced', sa.DateTime(), nullable=True, comment='Timestamp of last GitHub sync'),
    sa.Column('resume_uploaded', sa.Boolean(), nullable=False, comment='Whether resume has been uploaded'),
    sa.Column('resume_file_url', sa.Text(), nullable=True, comment='URL to uploaded resume file'),
    sa.Column('resume_text', sa.Text(), nullable=True, comment='Extracted text content from resume'),
    sa.Column('resume_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured JSON data from resume parsing'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the profile was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When the profile was last modified'),
    sa.ForeignKeyConstraint(['user_id'], ['users.clerk_user_id'], name=op.f('profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    comment='User profile information and professional details'
    )
    op.create_index('idx_profile_github_user_id', 'profiles', ['github_user_id'], unique=False)
    op.create_index('idx_profile_user_id', 'profiles', ['user_id'], unique=False)
    
    # Check if idx_profiles_location_geog index exists before creating it
    # This handles the case where the index was created manually or in a previous failed migration
    try:
        bind = op.get_bind()
        inspector = inspect(bind)
        existing_profiles_indexes = [idx['name'] for idx in inspector.get_indexes('profiles')]
        if 'idx_profiles_location_geog' not in existing_profiles_indexes:
            op.create_index('idx_profiles_location_geog', 'profiles', ['location_geog'], unique=False, postgresql_using='gist')
    except Exception:
        # If check fails, try to create the index anyway (will fail gracefully if it exists)
        try:
            op.create_index('idx_profiles_location_geog', 'profiles', ['location_geog'], unique=False, postgresql_using='gist')
        except Exception:
            pass  # Index already exists, which is fine
    
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index('idx_profiles_location_geog', table_name='profiles', postgresql_using='gist')
    op.drop_index('idx_profile_user_id', table_name='profiles')
    op.drop_index('idx_profile_github_user_id', table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_index('idx_posts_location_geog', table_name='posts', postgresql_using='gist')
    op.drop_index('idx_post_type', table_name='posts')
    op.drop_index('idx_post_created_at', table_name='posts')
    op.drop_index('idx_post_author_id', table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_github_accounts_user_id'), table_name='github_accounts')
    op.drop_index(op.f('ix_github_accounts_id'), table_name='github_accounts')
    op.drop_index(op.f('ix_github_accounts_github_user_id'), table_name='github_accounts')
    op.drop_index('idx_github_account_user_id', table_name='github_accounts')
    op.drop_index('idx_github_account_github_user_id', table_name='github_accounts')
    op.drop_table('github_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
