"""add_interactions

Revision ID: 2421de911768
Revises: 898e7d3131ee
Create Date: 2025-12-11 17:48:47.110599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = '2421de911768'
down_revision: Union[str, None] = '898e7d3131ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_sync_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('qdrant_synced', sa.Boolean(), nullable=False),
    sa.Column('qdrant_collection', sa.String(length=100), nullable=True),
    sa.Column('neo4j_synced', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_sync_status')),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_sync_entity')
    )
    op.create_index('idx_sync_entity_type', 'embedding_sync_status', ['entity_type'], unique=False)
    op.create_index('idx_sync_pending', 'embedding_sync_status', ['qdrant_synced', 'neo4j_synced'], unique=False)
    op.create_index(op.f('ix_embedding_sync_status_id'), 'embedding_sync_status', ['id'], unique=False)
    op.create_table('github_repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('html_url', sa.String(length=512), nullable=False),
    sa.Column('clone_url', sa.String(length=512), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('primary_language', sa.String(length=100), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('stars_count', sa.Integer(), nullable=True),
    sa.Column('forks_count', sa.Integer(), nullable=True),
    sa.Column('watchers_count', sa.Integer(), nullable=True),
    sa.Column('open_issues_count', sa.Integer(), nullable=True),
    sa.Column('is_fork', sa.Boolean(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('default_branch', sa.String(length=100), nullable=True),
    sa.Column('size_kb', sa.Integer(), nullable=True),
    sa.Column('license_name', sa.String(length=100), nullable=True),
    sa.Column('readme_content', sa.Text(), nullable=True),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('frameworks_detected', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_push_at', sa.DateTime(), nullable=True),
    sa.Column('repo_created_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.clerk_user_id'], name=op.f('github_repositories_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_repositories'))
    )
    op.create_index('idx_github_repo_languages', 'github_repositories', ['languages'], unique=False, postgresql_using='gin')
    op.create_index('idx_github_repo_topics', 'github_repositories', ['topics'], unique=False, postgresql_using='gin')
    op.create_index('idx_github_repo_user_id', 'github_repositories', ['user_id'], unique=False)
    op.create_index(op.f('ix_github_repositories_github_repo_id'), 'github_repositories', ['github_repo_id'], unique=True)
    op.create_index(op.f('ix_github_repositories_id'), 'github_repositories', ['id'], unique=False)
    op.create_index(op.f('ix_github_repositories_user_id'), 'github_repositories', ['user_id'], unique=False)
    op.create_table('user_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.String(length=255), nullable=False),
    sa.Column('following_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.clerk_user_id'], name=op.f('user_follows_follower_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.clerk_user_id'], name=op.f('user_follows_following_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_follows')),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follow')
    )
    op.create_index('idx_follower', 'user_follows', ['follower_id'], unique=False)
    op.create_index('idx_following', 'user_follows', ['following_id'], unique=False)
    op.create_index(op.f('ix_user_follows_id'), 'user_follows', ['id'], unique=False)
    op.create_table('post_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=30), nullable=False),
    sa.Column('interaction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('post_interactions_post_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.clerk_user_id'], name=op.f('post_interactions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_interactions')),
    sa.UniqueConstraint('user_id', 'post_id', 'interaction_type', name='uq_user_post_interaction')
    )
    op.create_index('idx_interaction_type_created', 'post_interactions', ['interaction_type', 'created_at'], unique=False)
    op.create_index('idx_interaction_user_post', 'post_interactions', ['user_id', 'post_id'], unique=False)
    op.create_index(op.f('ix_post_interactions_id'), 'post_interactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_interactions_id'), table_name='post_interactions')
    op.drop_index('idx_interaction_user_post', table_name='post_interactions')
    op.drop_index('idx_interaction_type_created', table_name='post_interactions')
    op.drop_table('post_interactions')
    op.drop_index(op.f('ix_user_follows_id'), table_name='user_follows')
    op.drop_index('idx_following', table_name='user_follows')
    op.drop_index('idx_follower', table_name='user_follows')
    op.drop_table('user_follows')
    op.drop_index(op.f('ix_github_repositories_user_id'), table_name='github_repositories')
    op.drop_index(op.f('ix_github_repositories_id'), table_name='github_repositories')
    op.drop_index(op.f('ix_github_repositories_github_repo_id'), table_name='github_repositories')
    op.drop_index('idx_github_repo_user_id', table_name='github_repositories')
    op.drop_index('idx_github_repo_topics', table_name='github_repositories', postgresql_using='gin')
    op.drop_index('idx_github_repo_languages', table_name='github_repositories', postgresql_using='gin')
    op.drop_table('github_repositories')
    op.drop_index(op.f('ix_embedding_sync_status_id'), table_name='embedding_sync_status')
    op.drop_index('idx_sync_pending', table_name='embedding_sync_status')
    op.drop_index('idx_sync_entity_type', table_name='embedding_sync_status')
    op.drop_table('embedding_sync_status')
    # ### end Alembic commands ###
