"""added_channelsproject_images

Revision ID: 5d7383e0d5a6
Revises: h4c5d6e7f8g9
Create Date: 2025-12-29 20:23:22.613337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d7383e0d5a6'
down_revision: Union[str, None] = 'h4c5d6e7f8g9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Create channels table first (no dependencies)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for channel'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='Foreign key to projects table'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Channel name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Channel description'),
    sa.Column('channel_type', sa.String(length=20), nullable=False, comment="Channel type: 'text', 'voice', 'announcement'"),
    sa.Column('visibility', sa.String(length=20), nullable=False, comment="Channel visibility: 'public' or 'private'"),
    sa.Column('created_by', sa.String(length=255), nullable=True, comment='User who created the channel'),
    sa.Column('is_archived', sa.Boolean(), nullable=False, comment='Whether channel is archived'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Whether this is the default channel for the project'),
    sa.Column('member_count', sa.Integer(), nullable=False, comment='Number of members in the channel'),
    sa.Column('last_message_at', sa.DateTime(), nullable=True, comment='Timestamp of last message in channel'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the channel was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When the channel was last updated'),
    sa.CheckConstraint("channel_type IN ('text', 'voice', 'announcement')", name=op.f('ck_channels_ck_channel_type')),
    sa.CheckConstraint("visibility IN ('public', 'private')", name=op.f('ck_channels_ck_channel_visibility')),
    sa.ForeignKeyConstraint(['created_by'], ['users.clerk_user_id'], name=op.f('channels_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('channels_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels')),
    comment='Channels for project communication'
    )
    op.create_index('idx_channel_created_by', 'channels', ['created_by'], unique=False)
    op.create_index('idx_channel_is_default', 'channels', ['is_default'], unique=False)
    op.create_index('idx_channel_project', 'channels', ['project_id'], unique=False)
    op.create_index('idx_channel_type', 'channels', ['channel_type'], unique=False)
    op.create_index('idx_channel_visibility', 'channels', ['visibility'], unique=False)
    op.create_index(op.f('ix_channels_created_by'), 'channels', ['created_by'], unique=False)
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_index(op.f('ix_channels_project_id'), 'channels', ['project_id'], unique=False)
    
    # Step 2: Create channel_messages WITHOUT thread_id foreign key to avoid circular dependency
    op.create_table('channel_messages',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for channel message'),
    sa.Column('public_id', sa.UUID(), nullable=False, comment='Public UUID for message (used in real-time)'),
    sa.Column('channel_id', sa.Integer(), nullable=False, comment='Foreign key to channels table'),
    sa.Column('sender_id', sa.String(length=255), nullable=True, comment='Foreign key to users table (message sender)'),
    sa.Column('content', sa.Text(), nullable=True, comment='Message content'),
    sa.Column('message_type', sa.String(length=30), nullable=False, comment="Message type: 'text', 'image', 'file', 'system', 'reply'"),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Message attachments: [{type, url, name, size, mime_type}]'),
    sa.Column('thread_id', sa.Integer(), nullable=True, comment='Foreign key to thread if this is a reply'),
    sa.Column('reply_to_message_id', sa.Integer(), nullable=True, comment='Foreign key to parent message if this is a reply'),
    sa.Column('reply_count', sa.Integer(), nullable=False, comment='Number of replies to this message'),
    sa.Column('reaction_count', sa.Integer(), nullable=False, comment='Total number of reactions'),
    sa.Column('mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of mentioned user IDs'),
    sa.Column('is_edited', sa.Boolean(), nullable=False, comment='Whether message has been edited'),
    sa.Column('edited_at', sa.DateTime(), nullable=True, comment='When message was last edited'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Whether message has been soft deleted'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When message was deleted'),
    sa.Column('is_pinned', sa.Boolean(), nullable=False, comment='Whether message is pinned'),
    sa.Column('pinned_at', sa.DateTime(), nullable=True, comment='When message was pinned'),
    sa.Column('pinned_by', sa.String(length=255), nullable=True, comment='User who pinned the message'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When message was sent'),
    sa.CheckConstraint("message_type IN ('text', 'image', 'file', 'system', 'reply')", name=op.f('ck_channel_messages_ck_channel_message_type')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('channel_messages_channel_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pinned_by'], ['users.clerk_user_id'], name=op.f('channel_messages_pinned_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['channel_messages.id'], name=op.f('channel_messages_reply_to_message_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.clerk_user_id'], name=op.f('channel_messages_sender_id_fkey'), ondelete='SET NULL'),
    # thread_id foreign key will be added after channel_threads table is created
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_messages')),
    comment='Channel messages for real-time communication'
    )
    op.create_index('idx_channel_message_channel', 'channel_messages', ['channel_id'], unique=False)
    op.create_index('idx_channel_message_created', 'channel_messages', ['created_at'], unique=False)
    op.create_index('idx_channel_message_pinned', 'channel_messages', ['is_pinned'], unique=False)
    op.create_index('idx_channel_message_sender', 'channel_messages', ['sender_id'], unique=False)
    op.create_index('idx_channel_message_thread', 'channel_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_channel_messages_channel_id'), 'channel_messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_messages_created_at'), 'channel_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_channel_messages_id'), 'channel_messages', ['id'], unique=False)
    op.create_index(op.f('ix_channel_messages_public_id'), 'channel_messages', ['public_id'], unique=True)
    op.create_index(op.f('ix_channel_messages_sender_id'), 'channel_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_channel_messages_thread_id'), 'channel_messages', ['thread_id'], unique=False)
    op.create_table('channel_threads',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for thread'),
    sa.Column('channel_id', sa.Integer(), nullable=False, comment='Foreign key to channels table'),
    sa.Column('root_message_id', sa.Integer(), nullable=False, comment='Foreign key to the root message that started the thread'),
    sa.Column('reply_count', sa.Integer(), nullable=False, comment='Number of replies in the thread'),
    sa.Column('last_reply_at', sa.DateTime(), nullable=True, comment='Timestamp of last reply in thread'),
    sa.Column('participant_ids', postgresql.ARRAY(sa.Integer()), nullable=True, comment='List of user IDs who participated in the thread'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the thread was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When the thread was last updated'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('channel_threads_channel_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_message_id'], ['channel_messages.id'], name=op.f('channel_threads_root_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_threads')),
    comment='Threads for channel message replies'
    )
    op.create_index('idx_channel_thread_channel', 'channel_threads', ['channel_id'], unique=False)
    op.create_index('idx_channel_thread_last_reply', 'channel_threads', ['last_reply_at'], unique=False)
    op.create_index('idx_channel_thread_root_message', 'channel_threads', ['root_message_id'], unique=False)
    op.create_index(op.f('ix_channel_threads_channel_id'), 'channel_threads', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_threads_id'), 'channel_threads', ['id'], unique=False)
    op.create_index(op.f('ix_channel_threads_root_message_id'), 'channel_threads', ['root_message_id'], unique=True)
    
    # Now add the circular foreign key constraint from channel_messages to channel_threads
    op.create_foreign_key(
        op.f('channel_messages_thread_id_fkey'),
        'channel_messages', 'channel_threads',
        ['thread_id'], ['id'],
        ondelete='SET NULL'
    )
    
    op.create_table('channel_message_reactions',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for reaction'),
    sa.Column('message_id', sa.Integer(), nullable=False, comment='Foreign key to channel_messages table'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='Foreign key to users table'),
    sa.Column('emoji', sa.String(length=50), nullable=False, comment='Emoji reaction (emoji character or shortcode)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the reaction was added'),
    sa.ForeignKeyConstraint(['message_id'], ['channel_messages.id'], name=op.f('channel_message_reactions_message_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.clerk_user_id'], name=op.f('channel_message_reactions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_message_reactions')),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='uq_channel_message_reaction'),
    comment='Reactions on channel messages'
    )
    op.create_index('idx_channel_reaction_emoji', 'channel_message_reactions', ['emoji'], unique=False)
    op.create_index('idx_channel_reaction_message', 'channel_message_reactions', ['message_id'], unique=False)
    op.create_index('idx_channel_reaction_user', 'channel_message_reactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_channel_message_reactions_id'), 'channel_message_reactions', ['id'], unique=False)
    op.create_index(op.f('ix_channel_message_reactions_message_id'), 'channel_message_reactions', ['message_id'], unique=False)
    op.create_index(op.f('ix_channel_message_reactions_user_id'), 'channel_message_reactions', ['user_id'], unique=False)
    
    # Step 3: Create project_completions table
    op.create_table('project_completions',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for project completion'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='Foreign key to projects table'),
    sa.Column('completed_by', sa.String(length=255), nullable=False, comment='User who marked the project as complete'),
    sa.Column('completion_text', sa.Text(), nullable=True, comment='Summary text describing the project completion'),
    sa.Column('completion_attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Attachments: {images: [], files: [], links: []}'),
    sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of achievements/milestones completed'),
    sa.Column('testimonials', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Testimonials from team members: [{user_id, text, rating, created_at}]'),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Project metrics: {duration_days, team_size, commits, etc.}'),
    sa.Column('is_featured', sa.Boolean(), nullable=False, comment='Whether this completion is featured in success stories'),
    sa.Column('featured_at', sa.DateTime(), nullable=True, comment='When the completion was featured'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the project was marked complete'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When the completion was last updated'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.clerk_user_id'], name=op.f('project_completions_completed_by_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_completions_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_completions')),
    comment='Project completion records for success stories'
    )
    op.create_index('idx_project_completion_completed_by', 'project_completions', ['completed_by'], unique=False)
    op.create_index('idx_project_completion_created', 'project_completions', ['created_at'], unique=False)
    op.create_index('idx_project_completion_featured', 'project_completions', ['is_featured'], unique=False)
    op.create_index('idx_project_completion_project', 'project_completions', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_completions_completed_by'), 'project_completions', ['completed_by'], unique=False)
    op.create_index(op.f('ix_project_completions_id'), 'project_completions', ['id'], unique=False)
    op.create_index(op.f('ix_project_completions_project_id'), 'project_completions', ['project_id'], unique=True)
    
    # Step 4: Create channel_members table
    op.create_table('channel_members',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for channel member'),
    sa.Column('channel_id', sa.Integer(), nullable=False, comment='Foreign key to channels table'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='Foreign key to users table'),
    sa.Column('role', sa.String(length=20), nullable=False, comment="Member role: 'admin' or 'member'"),
    sa.Column('notifications', sa.String(length=20), nullable=False, comment="Notification preference: 'all', 'mentions', 'none'"),
    sa.Column('last_read_at', sa.DateTime(), nullable=True, comment='Timestamp of last read message'),
    sa.Column('last_seen_message_id', sa.UUID(), nullable=True, comment='UUID of last seen message'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When member joined the channel'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When member record was last updated'),
    sa.CheckConstraint("notifications IN ('all', 'mentions', 'none')", name=op.f('ck_channel_members_ck_channel_member_notifications')),
    sa.CheckConstraint("role IN ('admin', 'member')", name=op.f('ck_channel_members_ck_channel_member_role')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('channel_members_channel_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.clerk_user_id'], name=op.f('channel_members_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_members')),
    sa.UniqueConstraint('channel_id', 'user_id', name='uq_channel_member'),
    comment='Channel membership records'
    )
    op.create_index('idx_channel_member_channel', 'channel_members', ['channel_id'], unique=False)
    op.create_index('idx_channel_member_role', 'channel_members', ['role'], unique=False)
    op.create_index('idx_channel_member_user', 'channel_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_channel_members_channel_id'), 'channel_members', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_members_id'), 'channel_members', ['id'], unique=False)
    op.create_index(op.f('ix_channel_members_user_id'), 'channel_members', ['user_id'], unique=False)
    
    # Drop old tables from previous running/fitness app (these are not in the current models)
    # IMPORTANT: Drop in correct order - child tables first, then parent tables
    
    # Level 1: Drop most dependent tables (no other tables depend on these)
    op.drop_index(op.f('Comment_parentId_idx'), table_name='Comment')
    op.drop_index(op.f('Comment_postId_idx'), table_name='Comment')
    op.drop_index(op.f('Comment_userId_idx'), table_name='Comment')
    op.drop_table('Comment')
    
    op.drop_index(op.f('CapturedAreaCoordinate_areaId_idx'), table_name='CapturedAreaCoordinate')
    op.drop_table('CapturedAreaCoordinate')
    
    op.drop_index(op.f('ConversationParticipant_conversationId_idx'), table_name='ConversationParticipant')
    op.drop_index(op.f('ConversationParticipant_conversationId_userId_key'), table_name='ConversationParticipant')
    op.drop_index(op.f('ConversationParticipant_userId_idx'), table_name='ConversationParticipant')
    op.drop_table('ConversationParticipant')
    
    op.drop_index(op.f('EventParticipant_eventId_idx'), table_name='EventParticipant')
    op.drop_index(op.f('EventParticipant_userId_eventId_key'), table_name='EventParticipant')
    op.drop_table('EventParticipant')
    
    op.drop_index(op.f('RunSplit_runId_idx'), table_name='RunSplit')
    op.drop_table('RunSplit')
    
    op.drop_index(op.f('RunCoordinate_runId_idx'), table_name='RunCoordinate')
    op.drop_index(op.f('RunCoordinate_timestamp_idx'), table_name='RunCoordinate')
    op.drop_table('RunCoordinate')
    
    op.drop_index(op.f('RunPhoto_runId_idx'), table_name='RunPhoto')
    op.drop_table('RunPhoto')
    
    op.drop_index(op.f('Message_conversationId_idx'), table_name='Message')
    op.drop_index(op.f('Message_createdAt_idx'), table_name='Message')
    op.drop_index(op.f('Message_senderId_idx'), table_name='Message')
    op.drop_table('Message')
    
    op.drop_index(op.f('GroupMember_groupId_idx'), table_name='GroupMember')
    op.drop_index(op.f('GroupMember_userId_groupId_key'), table_name='GroupMember')
    op.drop_table('GroupMember')
    
    op.drop_index(op.f('RouteLike_routeId_idx'), table_name='RouteLike')
    op.drop_index(op.f('RouteLike_userId_routeId_key'), table_name='RouteLike')
    op.drop_table('RouteLike')
    
    op.drop_index(op.f('UserAchievement_userId_achievementId_key'), table_name='UserAchievement')
    op.drop_index(op.f('UserAchievement_userId_idx'), table_name='UserAchievement')
    op.drop_table('UserAchievement')
    
    op.drop_index(op.f('Like_postId_idx'), table_name='Like')
    op.drop_index(op.f('Like_userId_postId_key'), table_name='Like')
    op.drop_table('Like')
    
    op.drop_index(op.f('Notification_createdAt_idx'), table_name='Notification')
    op.drop_index(op.f('Notification_isRead_idx'), table_name='Notification')
    op.drop_index(op.f('Notification_userId_idx'), table_name='Notification')
    op.drop_table('Notification')
    
    op.drop_index(op.f('Follow_followerId_followingId_key'), table_name='Follow')
    op.drop_index(op.f('Follow_followerId_idx'), table_name='Follow')
    op.drop_index(op.f('Follow_followingId_idx'), table_name='Follow')
    op.drop_table('Follow')
    
    op.drop_index(op.f('RouteCoordinate_routeId_idx'), table_name='RouteCoordinate')
    op.drop_table('RouteCoordinate')
    
    # Level 2: Drop tables that were referenced by Level 1
    op.drop_index(op.f('CapturedArea_area_idx'), table_name='CapturedArea')
    op.drop_index(op.f('CapturedArea_userId_idx'), table_name='CapturedArea')
    op.drop_table('CapturedArea')
    
    op.drop_index(op.f('GroupEvent_groupId_idx'), table_name='GroupEvent')
    op.drop_index(op.f('GroupEvent_startTime_idx'), table_name='GroupEvent')
    op.drop_index(op.f('GroupEvent_status_idx'), table_name='GroupEvent')
    op.drop_table('GroupEvent')
    
    # Post must be dropped before Run (Post has FK to Run)
    op.drop_index(op.f('Post_createdAt_idx'), table_name='Post')
    op.drop_index(op.f('Post_latitude_longitude_idx'), table_name='Post')
    op.drop_index(op.f('Post_userId_idx'), table_name='Post')
    op.drop_table('Post')
    
    op.drop_index(op.f('Run_createdAt_idx'), table_name='Run')
    op.drop_index(op.f('Run_isCompleted_idx'), table_name='Run')
    op.drop_index(op.f('Run_routeId_idx'), table_name='Run')
    op.drop_index(op.f('Run_userId_idx'), table_name='Run')
    op.drop_table('Run')
    
    op.drop_index(op.f('Conversation_updatedAt_idx'), table_name='Conversation')
    op.drop_table('Conversation')
    
    # Level 3: Drop parent tables
    op.drop_index(op.f('Route_city_idx'), table_name='Route')
    op.drop_index(op.f('Route_difficulty_idx'), table_name='Route')
    op.drop_index(op.f('Route_isPublic_idx'), table_name='Route')
    op.drop_index(op.f('Route_userId_idx'), table_name='Route')
    op.drop_table('Route')
    
    op.drop_index(op.f('Group_city_idx'), table_name='Group')
    op.drop_index(op.f('Group_ownerId_idx'), table_name='Group')
    op.drop_table('Group')
    
    op.drop_index(op.f('Achievement_name_key'), table_name='Achievement')
    op.drop_table('Achievement')
    
    op.drop_index(op.f('User_clerkId_idx'), table_name='User')
    op.drop_index(op.f('User_clerkId_key'), table_name='User')
    op.drop_index(op.f('User_email_key'), table_name='User')
    op.drop_index(op.f('User_latitude_longitude_idx'), table_name='User')
    op.drop_index(op.f('User_username_idx'), table_name='User')
    op.drop_index(op.f('User_username_key'), table_name='User')
    op.drop_table('User')
    
    # Drop Prisma migrations table
    op.drop_table('_prisma_migrations')
    
    # Modify existing tables (add/update columns and indexes)
    op.drop_index(op.f('idx_group_message_public_id'), table_name='group_messages')
    op.drop_constraint(op.f('uq_group_message_public_id'), 'group_messages', type_='unique')
    op.create_index(op.f('ix_group_messages_public_id'), 'group_messages', ['public_id'], unique=True)
    op.add_column('posts', sa.Column('request_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Request post details: {compensation_type, stipend_amount, stipend_currency, duration_type, duration_value, work_type, location, application_deadline, positions_available}'))
    op.create_index('idx_post_author_created', 'posts', ['author_id', 'created_at'], unique=False)
    op.create_index('idx_post_skills_gin', 'posts', ['skills'], unique=False, postgresql_using='gin')
    op.create_index('idx_post_tags_gin', 'posts', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_posts_project_id'), 'posts', ['project_id'], unique=False)
    op.add_column('profiles', sa.Column('google_connected', sa.Boolean(), nullable=False, server_default='false', comment='Whether Google Calendar is connected'))
    op.add_column('profiles', sa.Column('google_user_id', sa.Text(), nullable=True, comment='Google user ID if connected'))
    op.add_column('profiles', sa.Column('google_email', sa.Text(), nullable=True, comment='Google email if connected'))
    op.add_column('profiles', sa.Column('google_access_token', sa.Text(), nullable=True, comment='Google OAuth access token'))
    op.add_column('profiles', sa.Column('google_refresh_token', sa.Text(), nullable=True, comment='Google OAuth refresh token'))
    op.add_column('profiles', sa.Column('google_token_expires_at', sa.DateTime(), nullable=True, comment='When Google access token expires'))
    op.add_column('profiles', sa.Column('google_calendar_id', sa.Text(), nullable=True, comment='Primary Google Calendar ID for events'))
    op.add_column('profiles', sa.Column('google_last_synced', sa.DateTime(), nullable=True, comment='Timestamp of last Google Calendar sync'))
    op.create_index('idx_profile_google_user_id', 'profiles', ['google_user_id'], unique=False)
    op.add_column('projects', sa.Column('image_url', sa.Text(), nullable=True, comment='Project cover image URL'))
    op.alter_column('push_tokens', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               comment='User who owns this push token',
               existing_nullable=False)
    op.alter_column('push_tokens', 'token',
               existing_type=sa.VARCHAR(length=255),
               comment='Expo push token (ExponentPushToken[...])',
               existing_nullable=False)
    op.alter_column('push_tokens', 'device_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Device platform (ios, android)',
               existing_nullable=True)
    op.alter_column('push_tokens', 'device_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Human-readable device name',
               existing_nullable=True)
    op.alter_column('push_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether this token is currently active',
               existing_nullable=False)
    op.alter_column('push_tokens', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='When the token was last used to send a notification',
               existing_nullable=True)
    op.drop_index(op.f('ix_push_tokens_user_active'), table_name='push_tokens')
    op.drop_constraint(op.f('push_tokens_token_key'), 'push_tokens', type_='unique')
    op.create_index('idx_push_token_user_active', 'push_tokens', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_push_tokens_id'), 'push_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_push_tokens_is_active'), 'push_tokens', ['is_active'], unique=False)
    op.create_index(op.f('ix_push_tokens_token'), 'push_tokens', ['token'], unique=True)
    op.create_foreign_key(op.f('push_tokens_user_id_fkey'), 'push_tokens', 'users', ['user_id'], ['clerk_user_id'], ondelete='CASCADE')
    op.create_table_comment(
        'push_tokens',
        'Expo push notification tokens for mobile devices',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'push_tokens',
        existing_comment='Expo push notification tokens for mobile devices',
        schema=None
    )
    op.drop_constraint(op.f('push_tokens_user_id_fkey'), 'push_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_push_tokens_token'), table_name='push_tokens')
    op.drop_index(op.f('ix_push_tokens_is_active'), table_name='push_tokens')
    op.drop_index(op.f('ix_push_tokens_id'), table_name='push_tokens')
    op.drop_index('idx_push_token_user_active', table_name='push_tokens')
    op.create_unique_constraint(op.f('push_tokens_token_key'), 'push_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_push_tokens_user_active'), 'push_tokens', ['user_id', 'is_active'], unique=False)
    op.alter_column('push_tokens', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When the token was last used to send a notification',
               existing_nullable=True)
    op.alter_column('push_tokens', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this token is currently active',
               existing_nullable=False)
    op.alter_column('push_tokens', 'device_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Human-readable device name',
               existing_nullable=True)
    op.alter_column('push_tokens', 'device_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Device platform (ios, android)',
               existing_nullable=True)
    op.alter_column('push_tokens', 'token',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Expo push token (ExponentPushToken[...])',
               existing_nullable=False)
    op.alter_column('push_tokens', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='User who owns this push token',
               existing_nullable=False)
    op.drop_column('projects', 'image_url')
    op.drop_index('idx_profile_google_user_id', table_name='profiles')
    op.drop_column('profiles', 'google_last_synced')
    op.drop_column('profiles', 'google_calendar_id')
    op.drop_column('profiles', 'google_token_expires_at')
    op.drop_column('profiles', 'google_refresh_token')
    op.drop_column('profiles', 'google_access_token')
    op.drop_column('profiles', 'google_email')
    op.drop_column('profiles', 'google_user_id')
    op.drop_column('profiles', 'google_connected')
    op.drop_index(op.f('ix_posts_project_id'), table_name='posts')
    op.drop_index('idx_post_tags_gin', table_name='posts', postgresql_using='gin')
    op.drop_index('idx_post_skills_gin', table_name='posts', postgresql_using='gin')
    op.drop_index('idx_post_author_created', table_name='posts')
    op.drop_column('posts', 'request_details')
    op.drop_index(op.f('ix_group_messages_public_id'), table_name='group_messages')
    op.create_unique_constraint(op.f('uq_group_message_public_id'), 'group_messages', ['public_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_group_message_public_id'), 'group_messages', ['public_id'], unique=True)
    op.create_table('Like',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('postId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['Post.id'], name=op.f('Like_postId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Like_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Like_pkey'))
    )
    op.create_index(op.f('Like_userId_postId_key'), 'Like', ['userId', 'postId'], unique=True)
    op.create_index(op.f('Like_postId_idx'), 'Like', ['postId'], unique=False)
    op.create_table('RunPhoto',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('runId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('imageUrl', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('takenAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['runId'], ['Run.id'], name=op.f('RunPhoto_runId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('RunPhoto_pkey'))
    )
    op.create_index(op.f('RunPhoto_runId_idx'), 'RunPhoto', ['runId'], unique=False)
    op.create_table('Conversation',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Conversation_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('Conversation_updatedAt_idx'), 'Conversation', ['updatedAt'], unique=False)
    op.create_table('Route',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('estimatedTime', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('difficulty', postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='Difficulty'), server_default=sa.text('\'EASY\'::"Difficulty"'), autoincrement=False, nullable=False),
    sa.Column('elevation', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('elevationGain', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('isPublic', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('thumbnailUrl', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timesRun', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('avgRating', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name='Route_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Route_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('Route_userId_idx'), 'Route', ['userId'], unique=False)
    op.create_index(op.f('Route_isPublic_idx'), 'Route', ['isPublic'], unique=False)
    op.create_index(op.f('Route_difficulty_idx'), 'Route', ['difficulty'], unique=False)
    op.create_index(op.f('Route_city_idx'), 'Route', ['city'], unique=False)
    op.create_table('Post',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('runId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('imageUrl', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('locationName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('isPublic', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['runId'], ['Run.id'], name='Post_runId_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name='Post_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Post_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('Post_userId_idx'), 'Post', ['userId'], unique=False)
    op.create_index(op.f('Post_latitude_longitude_idx'), 'Post', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('Post_createdAt_idx'), 'Post', ['createdAt'], unique=False)
    op.create_table('RouteCoordinate',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('routeId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('altitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['routeId'], ['Route.id'], name=op.f('RouteCoordinate_routeId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('RouteCoordinate_pkey'))
    )
    op.create_index(op.f('RouteCoordinate_routeId_idx'), 'RouteCoordinate', ['routeId'], unique=False)
    op.create_table('Notification',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fromUserId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('LIKE', 'COMMENT', 'FOLLOW', 'GROUP_INVITE', 'EVENT_REMINDER', 'ACHIEVEMENT', 'RUN_COMPLETED', 'NEARBY_RUNNER', 'MESSAGE', name='NotificationType'), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('postId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('runId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('groupId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('eventId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('isRead', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fromUserId'], ['User.id'], name=op.f('Notification_fromUserId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Notification_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Notification_pkey'))
    )
    op.create_index(op.f('Notification_userId_idx'), 'Notification', ['userId'], unique=False)
    op.create_index(op.f('Notification_isRead_idx'), 'Notification', ['isRead'], unique=False)
    op.create_index(op.f('Notification_createdAt_idx'), 'Notification', ['createdAt'], unique=False)
    op.create_table('Follow',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('followerId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('followingId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['followerId'], ['User.id'], name=op.f('Follow_followerId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['followingId'], ['User.id'], name=op.f('Follow_followingId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Follow_pkey'))
    )
    op.create_index(op.f('Follow_followingId_idx'), 'Follow', ['followingId'], unique=False)
    op.create_index(op.f('Follow_followerId_idx'), 'Follow', ['followerId'], unique=False)
    op.create_index(op.f('Follow_followerId_followingId_key'), 'Follow', ['followerId', 'followingId'], unique=True)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    )
    op.create_table('RunCoordinate',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('runId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('altitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('heading', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('heartRate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['runId'], ['Run.id'], name=op.f('RunCoordinate_runId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('RunCoordinate_pkey'))
    )
    op.create_index(op.f('RunCoordinate_timestamp_idx'), 'RunCoordinate', ['timestamp'], unique=False)
    op.create_index(op.f('RunCoordinate_runId_idx'), 'RunCoordinate', ['runId'], unique=False)
    op.create_table('GroupEvent',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('groupId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('routeId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creatorId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('startTime', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('endTime', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('meetingAddress', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meetingLat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('meetingLng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('maxParticipants', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('UPCOMING', 'ONGOING', 'COMPLETED', 'CANCELLED', name='EventStatus'), server_default=sa.text('\'UPCOMING\'::"EventStatus"'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['groupId'], ['Group.id'], name='GroupEvent_groupId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['routeId'], ['Route.id'], name='GroupEvent_routeId_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='GroupEvent_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('GroupEvent_status_idx'), 'GroupEvent', ['status'], unique=False)
    op.create_index(op.f('GroupEvent_startTime_idx'), 'GroupEvent', ['startTime'], unique=False)
    op.create_index(op.f('GroupEvent_groupId_idx'), 'GroupEvent', ['groupId'], unique=False)
    op.create_table('Run',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('routeId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('startTime', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('endTime', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('distance', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('avgPace', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('maxPace', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('minPace', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('calories', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('elevation', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('elevationGain', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('elevationLoss', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('isCompleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('isPaused', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('mapSnapshotUrl', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('weather', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['routeId'], ['Route.id'], name='Run_routeId_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name='Run_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Run_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('Run_userId_idx'), 'Run', ['userId'], unique=False)
    op.create_index(op.f('Run_routeId_idx'), 'Run', ['routeId'], unique=False)
    op.create_index(op.f('Run_isCompleted_idx'), 'Run', ['isCompleted'], unique=False)
    op.create_index(op.f('Run_createdAt_idx'), 'Run', ['createdAt'], unique=False)
    op.create_table('GroupMember',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('groupId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', name='GroupRole'), server_default=sa.text('\'MEMBER\'::"GroupRole"'), autoincrement=False, nullable=False),
    sa.Column('joinedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['groupId'], ['Group.id'], name=op.f('GroupMember_groupId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('GroupMember_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('GroupMember_pkey'))
    )
    op.create_index(op.f('GroupMember_userId_groupId_key'), 'GroupMember', ['userId', 'groupId'], unique=True)
    op.create_index(op.f('GroupMember_groupId_idx'), 'GroupMember', ['groupId'], unique=False)
    op.create_table('CapturedArea',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('area', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('perimeter', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('capturedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name='CapturedArea_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='CapturedArea_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('CapturedArea_userId_idx'), 'CapturedArea', ['userId'], unique=False)
    op.create_index(op.f('CapturedArea_area_idx'), 'CapturedArea', ['area'], unique=False)
    op.create_table('UserAchievement',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('achievementId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('unlockedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['achievementId'], ['Achievement.id'], name=op.f('UserAchievement_achievementId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('UserAchievement_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('UserAchievement_pkey'))
    )
    op.create_index(op.f('UserAchievement_userId_idx'), 'UserAchievement', ['userId'], unique=False)
    op.create_index(op.f('UserAchievement_userId_achievementId_key'), 'UserAchievement', ['userId', 'achievementId'], unique=True)
    op.create_table('RouteLike',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('routeId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['routeId'], ['Route.id'], name=op.f('RouteLike_routeId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('RouteLike_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('RouteLike_pkey'))
    )
    op.create_index(op.f('RouteLike_userId_routeId_key'), 'RouteLike', ['userId', 'routeId'], unique=True)
    op.create_index(op.f('RouteLike_routeId_idx'), 'RouteLike', ['routeId'], unique=False)
    op.create_table('Group',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('imageUrl', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ownerId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('isPublic', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Group_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('Group_ownerId_idx'), 'Group', ['ownerId'], unique=False)
    op.create_index(op.f('Group_city_idx'), 'Group', ['city'], unique=False)
    op.create_table('Message',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('conversationId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('senderId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('imageUrl', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('readAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversationId'], ['Conversation.id'], name=op.f('Message_conversationId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['senderId'], ['User.id'], name=op.f('Message_senderId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Message_pkey'))
    )
    op.create_index(op.f('Message_senderId_idx'), 'Message', ['senderId'], unique=False)
    op.create_index(op.f('Message_createdAt_idx'), 'Message', ['createdAt'], unique=False)
    op.create_index(op.f('Message_conversationId_idx'), 'Message', ['conversationId'], unique=False)
    op.create_table('RunSplit',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('runId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('km', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pace', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('elevation', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('avgHeartRate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['runId'], ['Run.id'], name=op.f('RunSplit_runId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('RunSplit_pkey'))
    )
    op.create_index(op.f('RunSplit_runId_idx'), 'RunSplit', ['runId'], unique=False)
    op.create_table('EventParticipant',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('eventId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('GOING', 'MAYBE', 'NOT_GOING', name='ParticipantStatus'), server_default=sa.text('\'GOING\'::"ParticipantStatus"'), autoincrement=False, nullable=False),
    sa.Column('joinedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['GroupEvent.id'], name=op.f('EventParticipant_eventId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('EventParticipant_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('EventParticipant_pkey'))
    )
    op.create_index(op.f('EventParticipant_userId_eventId_key'), 'EventParticipant', ['userId', 'eventId'], unique=True)
    op.create_index(op.f('EventParticipant_eventId_idx'), 'EventParticipant', ['eventId'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('clerkId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fullName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('avatarUrl', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lastLocationUpdate', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('isLocationPublic', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('totalDistance', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('totalRuns', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('totalTime', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('xp', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('isPublic', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('isCurrentlyRunning', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('currentRunId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='User_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('User_username_key'), 'User', ['username'], unique=True)
    op.create_index(op.f('User_username_idx'), 'User', ['username'], unique=False)
    op.create_index(op.f('User_latitude_longitude_idx'), 'User', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('User_email_key'), 'User', ['email'], unique=True)
    op.create_index(op.f('User_clerkId_key'), 'User', ['clerkId'], unique=True)
    op.create_index(op.f('User_clerkId_idx'), 'User', ['clerkId'], unique=False)
    op.create_table('ConversationParticipant',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('conversationId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('joinedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversationId'], ['Conversation.id'], name=op.f('ConversationParticipant_conversationId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('ConversationParticipant_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ConversationParticipant_pkey'))
    )
    op.create_index(op.f('ConversationParticipant_userId_idx'), 'ConversationParticipant', ['userId'], unique=False)
    op.create_index(op.f('ConversationParticipant_conversationId_userId_key'), 'ConversationParticipant', ['conversationId', 'userId'], unique=True)
    op.create_index(op.f('ConversationParticipant_conversationId_idx'), 'ConversationParticipant', ['conversationId'], unique=False)
    op.create_table('CapturedAreaCoordinate',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('areaId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['areaId'], ['CapturedArea.id'], name=op.f('CapturedAreaCoordinate_areaId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('CapturedAreaCoordinate_pkey'))
    )
    op.create_index(op.f('CapturedAreaCoordinate_areaId_idx'), 'CapturedAreaCoordinate', ['areaId'], unique=False)
    op.create_table('Achievement',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('icon', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('xpReward', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('TOTAL_DISTANCE', 'TOTAL_RUNS', 'STREAK', 'SINGLE_RUN_DISTANCE', 'SINGLE_RUN_PACE', 'CAPTURED_AREA', 'SOCIAL_FOLLOWERS', 'SOCIAL_POSTS', name='AchievementType'), autoincrement=False, nullable=False),
    sa.Column('threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Achievement_pkey'))
    )
    op.create_index(op.f('Achievement_name_key'), 'Achievement', ['name'], unique=True)
    op.create_table('Comment',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('postId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parentId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parentId'], ['Comment.id'], name=op.f('Comment_parentId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['postId'], ['Post.id'], name=op.f('Comment_postId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Comment_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Comment_pkey'))
    )
    op.create_index(op.f('Comment_userId_idx'), 'Comment', ['userId'], unique=False)
    op.create_index(op.f('Comment_postId_idx'), 'Comment', ['postId'], unique=False)
    op.create_index(op.f('Comment_parentId_idx'), 'Comment', ['parentId'], unique=False)
    op.drop_index(op.f('ix_channel_members_user_id'), table_name='channel_members')
    op.drop_index(op.f('ix_channel_members_id'), table_name='channel_members')
    op.drop_index(op.f('ix_channel_members_channel_id'), table_name='channel_members')
    op.drop_index('idx_channel_member_user', table_name='channel_members')
    op.drop_index('idx_channel_member_role', table_name='channel_members')
    op.drop_index('idx_channel_member_channel', table_name='channel_members')
    op.drop_table('channel_members')
    op.drop_index(op.f('ix_project_completions_project_id'), table_name='project_completions')
    op.drop_index(op.f('ix_project_completions_id'), table_name='project_completions')
    op.drop_index(op.f('ix_project_completions_completed_by'), table_name='project_completions')
    op.drop_index('idx_project_completion_project', table_name='project_completions')
    op.drop_index('idx_project_completion_featured', table_name='project_completions')
    op.drop_index('idx_project_completion_created', table_name='project_completions')
    op.drop_index('idx_project_completion_completed_by', table_name='project_completions')
    op.drop_table('project_completions')
    op.drop_index(op.f('ix_channels_project_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_created_by'), table_name='channels')
    op.drop_index('idx_channel_visibility', table_name='channels')
    op.drop_index('idx_channel_type', table_name='channels')
    op.drop_index('idx_channel_project', table_name='channels')
    op.drop_index('idx_channel_is_default', table_name='channels')
    op.drop_index('idx_channel_created_by', table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_channel_message_reactions_user_id'), table_name='channel_message_reactions')
    op.drop_index(op.f('ix_channel_message_reactions_message_id'), table_name='channel_message_reactions')
    op.drop_index(op.f('ix_channel_message_reactions_id'), table_name='channel_message_reactions')
    op.drop_index('idx_channel_reaction_user', table_name='channel_message_reactions')
    op.drop_index('idx_channel_reaction_message', table_name='channel_message_reactions')
    op.drop_index('idx_channel_reaction_emoji', table_name='channel_message_reactions')
    op.drop_table('channel_message_reactions')
    # Drop the circular foreign key constraint first
    op.drop_constraint(op.f('channel_messages_thread_id_fkey'), 'channel_messages', type_='foreignkey')
    
    op.drop_index(op.f('ix_channel_threads_root_message_id'), table_name='channel_threads')
    op.drop_index(op.f('ix_channel_threads_id'), table_name='channel_threads')
    op.drop_index(op.f('ix_channel_threads_channel_id'), table_name='channel_threads')
    op.drop_index('idx_channel_thread_root_message', table_name='channel_threads')
    op.drop_index('idx_channel_thread_last_reply', table_name='channel_threads')
    op.drop_index('idx_channel_thread_channel', table_name='channel_threads')
    op.drop_table('channel_threads')
    op.drop_index(op.f('ix_channel_messages_thread_id'), table_name='channel_messages')
    op.drop_index(op.f('ix_channel_messages_sender_id'), table_name='channel_messages')
    op.drop_index(op.f('ix_channel_messages_public_id'), table_name='channel_messages')
    op.drop_index(op.f('ix_channel_messages_id'), table_name='channel_messages')
    op.drop_index(op.f('ix_channel_messages_created_at'), table_name='channel_messages')
    op.drop_index(op.f('ix_channel_messages_channel_id'), table_name='channel_messages')
    op.drop_index('idx_channel_message_thread', table_name='channel_messages')
    op.drop_index('idx_channel_message_sender', table_name='channel_messages')
    op.drop_index('idx_channel_message_pinned', table_name='channel_messages')
    op.drop_index('idx_channel_message_created', table_name='channel_messages')
    op.drop_index('idx_channel_message_channel', table_name='channel_messages')
    op.drop_table('channel_messages')
    # ### end Alembic commands ###
