"""added_chatmessages

Revision ID: 898e7d3131ee
Revises: 075e4759c4a3
Create Date: 2025-11-27 21:47:21.157423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = '898e7d3131ee'
down_revision: Union[str, None] = '075e4759c4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for chat'),
    sa.Column('chat_type', sa.String(length=20), nullable=False, comment="Chat type: 'direct' (1-on-1) or 'group'"),
    sa.Column('name', sa.String(length=255), nullable=True, comment='Name of the chat (optional, mainly for group chats)'),
    sa.Column('created_by', sa.String(length=255), nullable=True, comment='User who created the chat'),
    sa.Column('participant_ids', postgresql.ARRAY(sa.String()), nullable=False, comment='Array of participant user IDs (clerk_user_id values)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the chat was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When the chat was last modified'),
    sa.Column('last_message_at', sa.DateTime(), nullable=True, comment='Timestamp of the last message in the chat'),
    sa.CheckConstraint("chat_type IN ('direct', 'group')", name=op.f('ck_chats_ck_chat_type')),
    sa.ForeignKeyConstraint(['created_by'], ['users.clerk_user_id'], name=op.f('chats_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats')),
    comment='Chat conversations between users'
    )
    op.create_index('idx_chat_created_by', 'chats', ['created_by'], unique=False)
    op.create_index('idx_chat_last_message_at', 'chats', ['last_message_at'], unique=False)
    op.create_index('idx_chat_type', 'chats', ['chat_type'], unique=False)
    op.create_index(op.f('ix_chats_created_by'), 'chats', ['created_by'], unique=False)
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for message'),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='Foreign key to chats table'),
    sa.Column('sender_id', sa.String(length=255), nullable=True, comment='Foreign key to users table (message sender)'),
    sa.Column('content', sa.Text(), nullable=True, comment='Message content/text'),
    sa.Column('message_type', sa.String(length=20), nullable=False, comment="Message type: 'text', 'image', 'file', 'system'"),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Message attachments (JSON structure with file URLs, types, etc.)'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='Timestamp when the message was read (for read receipts)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the message was created'),
    sa.CheckConstraint("message_type IN ('text', 'image', 'file', 'system')", name=op.f('ck_messages_ck_message_type')),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('messages_chat_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.clerk_user_id'], name=op.f('messages_sender_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    comment='Messages in chat conversations'
    )
    op.create_index('idx_message_chat_created_at', 'messages', ['chat_id', 'created_at'], unique=False)
    op.create_index('idx_message_chat_id', 'messages', ['chat_id'], unique=False)
    op.create_index('idx_message_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('idx_message_sender_id', 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_index('idx_message_sender_id', table_name='messages')
    op.drop_index('idx_message_created_at', table_name='messages')
    op.drop_index('idx_message_chat_id', table_name='messages')
    op.drop_index('idx_message_chat_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_created_by'), table_name='chats')
    op.drop_index('idx_chat_type', table_name='chats')
    op.drop_index('idx_chat_last_message_at', table_name='chats')
    op.drop_index('idx_chat_created_by', table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
