"""init

Revision ID: db6168b7357b
Revises: 
Create Date: 2026-02-16 23:29:11.332857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db6168b7357b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_sync_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('qdrant_synced', sa.Boolean(), nullable=False),
    sa.Column('qdrant_collection', sa.String(length=100), nullable=True),
    sa.Column('neo4j_synced', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_sync_status')),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_sync_entity')
    )
    op.create_index('idx_sync_entity_type', 'embedding_sync_status', ['entity_type'], unique=False)
    op.create_index('idx_sync_pending', 'embedding_sync_status', ['qdrant_synced', 'neo4j_synced'], unique=False)
    op.create_index(op.f('ix_embedding_sync_status_id'), 'embedding_sync_status', ['id'], unique=False)
    op.create_table('users',
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('mobile_number', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('clerk_user_id', name=op.f('pk_users')),
    comment='System users with Clerk authentication integration'
    )
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for chat'),
    sa.Column('chat_type', sa.String(length=20), nullable=False, comment="Chat type: 'direct' (1-on-1) or 'group'"),
    sa.Column('name', sa.String(length=255), nullable=True, comment='Name of the chat (optional, mainly for group chats)'),
    sa.Column('created_by', sa.String(length=255), nullable=True, comment='User who created the chat'),
    sa.Column('participant_ids', postgresql.ARRAY(sa.String()), nullable=False, comment='Array of participant user IDs (clerk_user_id values)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the chat was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When the chat was last modified'),
    sa.Column('last_message_at', sa.DateTime(), nullable=True, comment='Timestamp of the last message in the chat'),
    sa.CheckConstraint("chat_type IN ('direct', 'group')", name=op.f('ck_chats_ck_chat_type')),
    sa.ForeignKeyConstraint(['created_by'], ['users.clerk_user_id'], name=op.f('chats_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats')),
    comment='Chat conversations between users'
    )
    op.create_index('idx_chat_created_by', 'chats', ['created_by'], unique=False)
    op.create_index('idx_chat_last_message_at', 'chats', ['last_message_at'], unique=False)
    op.create_index('idx_chat_type', 'chats', ['chat_type'], unique=False)
    op.create_index(op.f('ix_chats_created_by'), 'chats', ['created_by'], unique=False)
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_table('cofounder_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.String(length=255), nullable=False),
    sa.Column('receiver_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'WITHDRAWN', name='matchstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('compatibility_score', sa.Float(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.clerk_user_id'], name=op.f('cofounder_matches_receiver_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.clerk_user_id'], name=op.f('cofounder_matches_sender_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cofounder_matches')),
    sa.UniqueConstraint('sender_id', 'receiver_id', name='uq_cofounder_match')
    )
    op.create_index('idx_match_created_at', 'cofounder_matches', ['created_at'], unique=False)
    op.create_index('idx_match_receiver_status', 'cofounder_matches', ['receiver_id', 'status'], unique=False)
    op.create_index('idx_match_sender_status', 'cofounder_matches', ['sender_id', 'status'], unique=False)
    op.create_index(op.f('ix_cofounder_matches_id'), 'cofounder_matches', ['id'], unique=False)
    op.create_index(op.f('ix_cofounder_matches_receiver_id'), 'cofounder_matches', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_cofounder_matches_sender_id'), 'cofounder_matches', ['sender_id'], unique=False)
    op.create_index(op.f('ix_cofounder_matches_status'), 'cofounder_matches', ['status'], unique=False)
    op.create_table('cofounder_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('elevator_pitch', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('impressive_accomplishment', sa.Text(), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('professional_experience', sa.Text(), nullable=True),
    sa.Column('technical_level', sa.Enum('NON_TECHNICAL', 'BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='technicallevel'), nullable=True),
    sa.Column('primary_roles', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('industries', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('employment_status', sa.Enum('EMPLOYED', 'SELF_EMPLOYED', 'STUDENT', 'BETWEEN_JOBS', name='employmentstatus'), nullable=True),
    sa.Column('commitment_timeline', sa.Enum('ALREADY_FULLTIME', 'READY_NOW', 'WITHIN_6_MONTHS', 'WITHIN_1_YEAR', 'EXPLORING', name='commitmenttimeline'), nullable=True),
    sa.Column('idea_status', sa.Enum('COMMITTED_TO_IDEA', 'HAVE_IDEAS_OPEN_TO_OTHERS', 'OPEN_TO_EXPLORE', name='ideastatus'), nullable=True),
    sa.Column('ideas_description', sa.Text(), nullable=True),
    sa.Column('has_cofounder', sa.Boolean(), nullable=False),
    sa.Column('responsibility_areas', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('equity_expectations', sa.Text(), nullable=True),
    sa.Column('remote_preference', sa.Enum('REMOTE', 'HYBRID', 'IN_PERSON', 'FLEXIBLE', name='remotepreference'), nullable=True),
    sa.Column('free_time', sa.Text(), nullable=True),
    sa.Column('life_story', sa.Text(), nullable=True),
    sa.Column('anything_else', sa.Text(), nullable=True),
    sa.Column('looking_for_description', sa.Text(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('completion_score', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.clerk_user_id'], name=op.f('cofounder_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cofounder_profiles'))
    )
    op.create_index('idx_cofounder_profile_complete', 'cofounder_profiles', ['is_complete'], unique=False)
    op.create_index('idx_cofounder_profile_user_id', 'cofounder_profiles', ['user_id'], unique=False)
    op.create_index('idx_cofounder_profile_visible', 'cofounder_profiles', ['is_visible'], unique=False)
    op.create_index(op.f('ix_cofounder_profiles_id'), 'cofounder_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_cofounder_profiles_user_id'), 'cofounder_profiles', ['user_id'], unique=True)
    op.create_table('github_accounts',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for GitHub account'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='Foreign key to users table'),
    sa.Column('github_user_id', sa.BigInteger(), nullable=False, comment='Unique GitHub user identifier'),
    sa.Column('username', sa.Text(), nullable=True, comment='GitHub username'),
    sa.Column('access_token', sa.Text(), nullable=True, comment='Encrypted GitHub OAuth access token'),
    sa.Column('token_scope', sa.Text(), nullable=True, comment='OAuth token scope/permissions'),
    sa.Column('follower_count', sa.Integer(), nullable=True, comment='Number of GitHub followers'),
    sa.Column('following_count', sa.Integer(), nullable=True, comment='Number of GitHub users being followed'),
    sa.Column('public_repos', sa.Integer(), nullable=True, comment='Number of public repositories'),
    sa.Column('last_synced', sa.DateTime(), nullable=False, comment='Timestamp of last sync with GitHub API'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the GitHub account was linked'),
    sa.ForeignKeyConstraint(['user_id'], ['users.clerk_user_id'], name=op.f('github_accounts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_accounts')),
    comment='GitHub account integration for users'
    )
    op.create_index('idx_github_account_github_user_id', 'github_accounts', ['github_user_id'], unique=False)
    op.create_index('idx_github_account_user_id', 'github_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_github_accounts_github_user_id'), 'github_accounts', ['github_user_id'], unique=True)
    op.create_index(op.f('ix_github_accounts_id'), 'github_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_github_accounts_user_id'), 'github_accounts', ['user_id'], unique=True)
    op.create_table('github_repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('html_url', sa.String(length=512), nullable=False),
    sa.Column('clone_url', sa.String(length=512), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('primary_language', sa.String(length=100), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('stars_count', sa.Integer(), nullable=True),
    sa.Column('forks_count', sa.Integer(), nullable=True),
    sa.Column('watchers_count', sa.Integer(), nullable=True),
    sa.Column('open_issues_count', sa.Integer(), nullable=True),
    sa.Column('is_fork', sa.Boolean(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('default_branch', sa.String(length=100), nullable=True),
    sa.Column('size_kb', sa.Integer(), nullable=True),
    sa.Column('license_name', sa.String(length=100), nullable=True),
    sa.Column('readme_content', sa.Text(), nullable=True),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('frameworks_detected', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_push_at', sa.DateTime(), nullable=True),
    sa.Column('repo_created_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.clerk_user_id'], name=op.f('github_repositories_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_repositories'))
    )
    op.create_index('idx_github_repo_languages', 'github_repositories', ['languages'], unique=False, postgresql_using='gin')
    op.create_index('idx_github_repo_topics', 'github_repositories', ['topics'], unique=False, postgresql_using='gin')
    op.create_index('idx_github_repo_user_id', 'github_repositories', ['user_id'], unique=False)
    op.create_index(op.f('ix_github_repositories_github_repo_id'), 'github_repositories', ['github_repo_id'], unique=True)
    op.create_index(op.f('ix_github_repositories_id'), 'github_repositories', ['id'], unique=False)
    op.create_index(op.f('ix_github_repositories_user_id'), 'github_repositories', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.String(length=255), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('notification_type', sa.Enum('FOLLOW', 'MESSAGE', 'SYSTEM', 'MATCH_REQUEST', 'MATCH_ACCEPTED', 'MATCH_DECLINED', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.clerk_user_id'], name=op.f('notifications_actor_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.clerk_user_id'], name=op.f('notifications_recipient_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('idx_notification_recipient_created', 'notifications', ['recipient_id', 'created_at'], unique=False)
    op.create_index('idx_notification_recipient_unread', 'notifications', ['recipient_id', 'is_read'], unique=False)
    op.create_index('idx_notification_type_created', 'notifications', ['notification_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_actor_id'), 'notifications', ['actor_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_table('profile_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viewer_id', sa.String(length=255), nullable=False),
    sa.Column('viewed_id', sa.String(length=255), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['viewed_id'], ['users.clerk_user_id'], name=op.f('profile_views_viewed_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.clerk_user_id'], name=op.f('profile_views_viewer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_views')),
    comment='Tracks which users have viewed which profiles'
    )
    op.create_index('idx_profile_view_viewed', 'profile_views', ['viewed_id', 'viewed_at'], unique=False)
    op.create_index('idx_profile_view_viewer', 'profile_views', ['viewer_id', 'viewed_at'], unique=False)
    op.create_index(op.f('ix_profile_views_id'), 'profile_views', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('timezone', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('pin', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('github_connected', sa.Boolean(), nullable=False),
    sa.Column('github_username', sa.Text(), nullable=True),
    sa.Column('github_user_id', sa.BigInteger(), nullable=True),
    sa.Column('github_last_synced', sa.DateTime(), nullable=True),
    sa.Column('resume_uploaded', sa.Boolean(), nullable=False),
    sa.Column('resume_file_url', sa.Text(), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('resume_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.clerk_user_id'], name=op.f('profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    op.create_index('idx_profile_github_user_id', 'profiles', ['github_user_id'], unique=False)
    op.create_index('idx_profile_user_id', 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('push_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='User who owns this push token'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='Expo push token (ExponentPushToken[...])'),
    sa.Column('device_type', sa.String(length=50), nullable=True, comment='Device platform (ios, android)'),
    sa.Column('device_name', sa.String(length=255), nullable=True, comment='Human-readable device name'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this token is currently active'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='When the token was last used to send a notification'),
    sa.ForeignKeyConstraint(['user_id'], ['users.clerk_user_id'], name=op.f('push_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_tokens')),
    comment='Expo push notification tokens for mobile devices'
    )
    op.create_index('idx_push_token_user_active', 'push_tokens', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_push_tokens_id'), 'push_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_push_tokens_is_active'), 'push_tokens', ['is_active'], unique=False)
    op.create_index(op.f('ix_push_tokens_token'), 'push_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_push_tokens_user_id'), 'push_tokens', ['user_id'], unique=False)
    op.create_table('user_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.String(length=255), nullable=False),
    sa.Column('following_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.clerk_user_id'], name=op.f('user_follows_follower_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.clerk_user_id'], name=op.f('user_follows_following_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_follows')),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follow')
    )
    op.create_index('idx_follower', 'user_follows', ['follower_id'], unique=False)
    op.create_index('idx_following', 'user_follows', ['following_id'], unique=False)
    op.create_index(op.f('ix_user_follows_id'), 'user_follows', ['id'], unique=False)
    op.create_table('user_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('target_user_id', sa.String(length=255), nullable=False),
    sa.Column('interaction_type', sa.String(length=30), nullable=False),
    sa.Column('interaction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.clerk_user_id'], name=op.f('user_interactions_target_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.clerk_user_id'], name=op.f('user_interactions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_interactions')),
    sa.UniqueConstraint('user_id', 'target_user_id', 'interaction_type', name='uq_user_interaction')
    )
    op.create_index('idx_user_interaction_target', 'user_interactions', ['target_user_id'], unique=False)
    op.create_index('idx_user_interaction_type', 'user_interactions', ['interaction_type'], unique=False)
    op.create_index('idx_user_interaction_user', 'user_interactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_interactions_id'), 'user_interactions', ['id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'PRO', name='subscriptiontier'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIALING', 'PAST_DUE', 'CANCELED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('polar_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('polar_customer_id', sa.String(length=255), nullable=True),
    sa.Column('polar_product_id', sa.String(length=255), nullable=True),
    sa.Column('billing_interval', sa.String(length=20), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.clerk_user_id'], name=op.f('user_subscriptions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_subscriptions')),
    sa.UniqueConstraint('polar_subscription_id', name=op.f('uq_user_subscriptions_polar_subscription_id')),
    comment='User subscription tracking for Polar.sh integration'
    )
    op.create_index('idx_subscription_polar_id', 'user_subscriptions', ['polar_subscription_id'], unique=False)
    op.create_index('idx_subscription_tier_status', 'user_subscriptions', ['tier', 'status'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key for message'),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='Foreign key to chats table'),
    sa.Column('sender_id', sa.String(length=255), nullable=True, comment='Foreign key to users table (message sender)'),
    sa.Column('content', sa.Text(), nullable=True, comment='Message content/text'),
    sa.Column('message_type', sa.String(length=20), nullable=False, comment="Message type: 'text', 'image', 'file', 'system'"),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Message attachments (JSON structure with file URLs, types, etc.)'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='Timestamp when the message was read (for read receipts)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the message was created'),
    sa.CheckConstraint("message_type IN ('text', 'image', 'file', 'system')", name=op.f('ck_messages_ck_message_type')),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('messages_chat_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.clerk_user_id'], name=op.f('messages_sender_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    comment='Messages in chat conversations'
    )
    op.create_index('idx_message_chat_created_at', 'messages', ['chat_id', 'created_at'], unique=False)
    op.create_index('idx_message_chat_id', 'messages', ['chat_id'], unique=False)
    op.create_index('idx_message_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('idx_message_sender_id', 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_index('idx_message_sender_id', table_name='messages')
    op.drop_index('idx_message_created_at', table_name='messages')
    op.drop_index('idx_message_chat_id', table_name='messages')
    op.drop_index('idx_message_chat_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_index('idx_subscription_tier_status', table_name='user_subscriptions')
    op.drop_index('idx_subscription_polar_id', table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_user_interactions_id'), table_name='user_interactions')
    op.drop_index('idx_user_interaction_user', table_name='user_interactions')
    op.drop_index('idx_user_interaction_type', table_name='user_interactions')
    op.drop_index('idx_user_interaction_target', table_name='user_interactions')
    op.drop_table('user_interactions')
    op.drop_index(op.f('ix_user_follows_id'), table_name='user_follows')
    op.drop_index('idx_following', table_name='user_follows')
    op.drop_index('idx_follower', table_name='user_follows')
    op.drop_table('user_follows')
    op.drop_index(op.f('ix_push_tokens_user_id'), table_name='push_tokens')
    op.drop_index(op.f('ix_push_tokens_token'), table_name='push_tokens')
    op.drop_index(op.f('ix_push_tokens_is_active'), table_name='push_tokens')
    op.drop_index(op.f('ix_push_tokens_id'), table_name='push_tokens')
    op.drop_index('idx_push_token_user_active', table_name='push_tokens')
    op.drop_table('push_tokens')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index('idx_profile_user_id', table_name='profiles')
    op.drop_index('idx_profile_github_user_id', table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_profile_views_id'), table_name='profile_views')
    op.drop_index('idx_profile_view_viewer', table_name='profile_views')
    op.drop_index('idx_profile_view_viewed', table_name='profile_views')
    op.drop_table('profile_views')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_actor_id'), table_name='notifications')
    op.drop_index('idx_notification_type_created', table_name='notifications')
    op.drop_index('idx_notification_recipient_unread', table_name='notifications')
    op.drop_index('idx_notification_recipient_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_github_repositories_user_id'), table_name='github_repositories')
    op.drop_index(op.f('ix_github_repositories_id'), table_name='github_repositories')
    op.drop_index(op.f('ix_github_repositories_github_repo_id'), table_name='github_repositories')
    op.drop_index('idx_github_repo_user_id', table_name='github_repositories')
    op.drop_index('idx_github_repo_topics', table_name='github_repositories', postgresql_using='gin')
    op.drop_index('idx_github_repo_languages', table_name='github_repositories', postgresql_using='gin')
    op.drop_table('github_repositories')
    op.drop_index(op.f('ix_github_accounts_user_id'), table_name='github_accounts')
    op.drop_index(op.f('ix_github_accounts_id'), table_name='github_accounts')
    op.drop_index(op.f('ix_github_accounts_github_user_id'), table_name='github_accounts')
    op.drop_index('idx_github_account_user_id', table_name='github_accounts')
    op.drop_index('idx_github_account_github_user_id', table_name='github_accounts')
    op.drop_table('github_accounts')
    op.drop_index(op.f('ix_cofounder_profiles_user_id'), table_name='cofounder_profiles')
    op.drop_index(op.f('ix_cofounder_profiles_id'), table_name='cofounder_profiles')
    op.drop_index('idx_cofounder_profile_visible', table_name='cofounder_profiles')
    op.drop_index('idx_cofounder_profile_user_id', table_name='cofounder_profiles')
    op.drop_index('idx_cofounder_profile_complete', table_name='cofounder_profiles')
    op.drop_table('cofounder_profiles')
    op.drop_index(op.f('ix_cofounder_matches_status'), table_name='cofounder_matches')
    op.drop_index(op.f('ix_cofounder_matches_sender_id'), table_name='cofounder_matches')
    op.drop_index(op.f('ix_cofounder_matches_receiver_id'), table_name='cofounder_matches')
    op.drop_index(op.f('ix_cofounder_matches_id'), table_name='cofounder_matches')
    op.drop_index('idx_match_sender_status', table_name='cofounder_matches')
    op.drop_index('idx_match_receiver_status', table_name='cofounder_matches')
    op.drop_index('idx_match_created_at', table_name='cofounder_matches')
    op.drop_table('cofounder_matches')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_created_by'), table_name='chats')
    op.drop_index('idx_chat_type', table_name='chats')
    op.drop_index('idx_chat_last_message_at', table_name='chats')
    op.drop_index('idx_chat_created_by', table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_embedding_sync_status_id'), table_name='embedding_sync_status')
    op.drop_index('idx_sync_pending', table_name='embedding_sync_status')
    op.drop_index('idx_sync_entity_type', table_name='embedding_sync_status')
    op.drop_table('embedding_sync_status')
    # ### end Alembic commands ###
